// <auto-generated />
using System;
using GSCMasterGuide.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GSCMasterGuide.Infrastructure.Migrations
{
    [DbContext(typeof(GSCDbContext))]
    [Migration("20220615002647_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("GSCMasterGuide.Domain.Entities.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsConsumable")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("GSCMasterGuide.Domain.Entities.Move", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Accuracy")
                        .HasColumnType("int");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Effect")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PP")
                        .HasColumnType("int");

                    b.Property<int>("Power")
                        .HasColumnType("int");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Moves");
                });

            modelBuilder.Entity("GSCMasterGuide.Domain.Entities.Pokemon", b =>
                {
                    b.Property<int>("NationalNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NationalNumber"), 1L, 1);

                    b.Property<int>("Attack")
                        .HasColumnType("int");

                    b.Property<int>("Defense")
                        .HasColumnType("int");

                    b.Property<int>("HP")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PreEvolutionNationalNumber")
                        .HasColumnType("int");

                    b.Property<int>("PrimaryType")
                        .HasColumnType("int");

                    b.Property<int>("SecondaryType")
                        .HasColumnType("int");

                    b.Property<int>("SpAttack")
                        .HasColumnType("int");

                    b.Property<int>("SpDefense")
                        .HasColumnType("int");

                    b.Property<int>("Speed")
                        .HasColumnType("int");

                    b.Property<int>("Tier")
                        .HasColumnType("int");

                    b.HasKey("NationalNumber");

                    b.HasIndex("PreEvolutionNationalNumber");

                    b.ToTable("Pokemon");
                });

            modelBuilder.Entity("GSCMasterGuide.Domain.Entities.PokemonMember", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<int>("AttackEV")
                        .HasColumnType("int");

                    b.Property<int>("AttackIV")
                        .HasColumnType("int");

                    b.Property<int>("DefenseEV")
                        .HasColumnType("int");

                    b.Property<int>("DefenseIV")
                        .HasColumnType("int");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<int>("HPEV")
                        .HasColumnType("int");

                    b.Property<int>("HPIV")
                        .HasColumnType("int");

                    b.Property<int>("Happiness")
                        .HasColumnType("int");

                    b.Property<bool>("IsShiny")
                        .HasColumnType("bit");

                    b.Property<int?>("ItemId")
                        .HasColumnType("int");

                    b.Property<int?>("MoveSlot1Id")
                        .HasColumnType("int");

                    b.Property<int?>("MoveSlot2Id")
                        .HasColumnType("int");

                    b.Property<int?>("MoveSlot3Id")
                        .HasColumnType("int");

                    b.Property<int?>("MoveSlot4Id")
                        .HasColumnType("int");

                    b.Property<string>("Nickname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PokemonNationalNumber")
                        .HasColumnType("int");

                    b.Property<int>("SpAttackEV")
                        .HasColumnType("int");

                    b.Property<int>("SpAttackIV")
                        .HasColumnType("int");

                    b.Property<int>("SpDefenseEV")
                        .HasColumnType("int");

                    b.Property<int>("SpDefenseIV")
                        .HasColumnType("int");

                    b.Property<int>("SpeedEV")
                        .HasColumnType("int");

                    b.Property<int>("SpeedIV")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("MoveSlot1Id");

                    b.HasIndex("MoveSlot2Id");

                    b.HasIndex("MoveSlot3Id");

                    b.HasIndex("MoveSlot4Id");

                    b.HasIndex("PokemonNationalNumber");

                    b.ToTable("PokemonMembers");
                });

            modelBuilder.Entity("GSCMasterGuide.Domain.Entities.PokemonMove", b =>
                {
                    b.Property<int>("MoveId")
                        .HasColumnType("int");

                    b.Property<int>("PokemonNationalNumber")
                        .HasColumnType("int");

                    b.HasKey("MoveId", "PokemonNationalNumber");

                    b.HasIndex("PokemonNationalNumber");

                    b.ToTable("PokemonMoves");
                });

            modelBuilder.Entity("GSCMasterGuide.Domain.Entities.PokemonTeam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<long?>("LeadId")
                        .HasColumnType("bigint");

                    b.Property<long?>("Member2Id")
                        .HasColumnType("bigint");

                    b.Property<long?>("Member3Id")
                        .HasColumnType("bigint");

                    b.Property<long?>("Member4Id")
                        .HasColumnType("bigint");

                    b.Property<long?>("Member5Id")
                        .HasColumnType("bigint");

                    b.Property<long?>("Member6Id")
                        .HasColumnType("bigint");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("TrainerId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("LeadId");

                    b.HasIndex("Member2Id");

                    b.HasIndex("Member3Id");

                    b.HasIndex("Member4Id");

                    b.HasIndex("Member5Id");

                    b.HasIndex("Member6Id");

                    b.HasIndex("TrainerId");

                    b.ToTable("PokemonTeams");
                });

            modelBuilder.Entity("GSCMasterGuide.Domain.Entities.Trainer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Trainers");
                });

            modelBuilder.Entity("GSCMasterGuide.Domain.Entities.Pokemon", b =>
                {
                    b.HasOne("GSCMasterGuide.Domain.Entities.Pokemon", "PreEvolution")
                        .WithMany("Evolutions")
                        .HasForeignKey("PreEvolutionNationalNumber");

                    b.Navigation("PreEvolution");
                });

            modelBuilder.Entity("GSCMasterGuide.Domain.Entities.PokemonMember", b =>
                {
                    b.HasOne("GSCMasterGuide.Domain.Entities.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId");

                    b.HasOne("GSCMasterGuide.Domain.Entities.Move", "MoveSlot1")
                        .WithMany()
                        .HasForeignKey("MoveSlot1Id");

                    b.HasOne("GSCMasterGuide.Domain.Entities.Move", "MoveSlot2")
                        .WithMany()
                        .HasForeignKey("MoveSlot2Id");

                    b.HasOne("GSCMasterGuide.Domain.Entities.Move", "MoveSlot3")
                        .WithMany()
                        .HasForeignKey("MoveSlot3Id");

                    b.HasOne("GSCMasterGuide.Domain.Entities.Move", "MoveSlot4")
                        .WithMany()
                        .HasForeignKey("MoveSlot4Id");

                    b.HasOne("GSCMasterGuide.Domain.Entities.Pokemon", "Pokemon")
                        .WithMany()
                        .HasForeignKey("PokemonNationalNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("MoveSlot1");

                    b.Navigation("MoveSlot2");

                    b.Navigation("MoveSlot3");

                    b.Navigation("MoveSlot4");

                    b.Navigation("Pokemon");
                });

            modelBuilder.Entity("GSCMasterGuide.Domain.Entities.PokemonMove", b =>
                {
                    b.HasOne("GSCMasterGuide.Domain.Entities.Move", "Move")
                        .WithMany()
                        .HasForeignKey("MoveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GSCMasterGuide.Domain.Entities.Pokemon", "Pokemon")
                        .WithMany()
                        .HasForeignKey("PokemonNationalNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Move");

                    b.Navigation("Pokemon");
                });

            modelBuilder.Entity("GSCMasterGuide.Domain.Entities.PokemonTeam", b =>
                {
                    b.HasOne("GSCMasterGuide.Domain.Entities.PokemonMember", "Lead")
                        .WithMany()
                        .HasForeignKey("LeadId");

                    b.HasOne("GSCMasterGuide.Domain.Entities.PokemonMember", "Member2")
                        .WithMany()
                        .HasForeignKey("Member2Id");

                    b.HasOne("GSCMasterGuide.Domain.Entities.PokemonMember", "Member3")
                        .WithMany()
                        .HasForeignKey("Member3Id");

                    b.HasOne("GSCMasterGuide.Domain.Entities.PokemonMember", "Member4")
                        .WithMany()
                        .HasForeignKey("Member4Id");

                    b.HasOne("GSCMasterGuide.Domain.Entities.PokemonMember", "Member5")
                        .WithMany()
                        .HasForeignKey("Member5Id");

                    b.HasOne("GSCMasterGuide.Domain.Entities.PokemonMember", "Member6")
                        .WithMany()
                        .HasForeignKey("Member6Id");

                    b.HasOne("GSCMasterGuide.Domain.Entities.Trainer", "Trainer")
                        .WithMany("PokemonTeams")
                        .HasForeignKey("TrainerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lead");

                    b.Navigation("Member2");

                    b.Navigation("Member3");

                    b.Navigation("Member4");

                    b.Navigation("Member5");

                    b.Navigation("Member6");

                    b.Navigation("Trainer");
                });

            modelBuilder.Entity("GSCMasterGuide.Domain.Entities.Pokemon", b =>
                {
                    b.Navigation("Evolutions");
                });

            modelBuilder.Entity("GSCMasterGuide.Domain.Entities.Trainer", b =>
                {
                    b.Navigation("PokemonTeams");
                });
#pragma warning restore 612, 618
        }
    }
}
